- name: Add admin group
  group:
    name: "{{ common_user }}"
    state: present

- name: Add local user
  user:
    name: "{{ common_user }}"
    group: "{{ common_user }}"
    shell: /bin/bash
    home: "/home/{{ common_user }}"
    create_home: yes
    state: present

- name: Add SSH public key for user
  authorized_key:
    user: "{{ common_user }}"
    key: "{{ common_pubkey }}"
    state: present

- name: Add sudoer rule for local user
  template:
    src: sudoers.j2
    dest: "/etc/sudoers.d/{{ common_user }}"
    owner: root
    group: root
    mode: 0440
    validate: /usr/sbin/visudo -csf %s